### ISSUE TITLE
Buradaki tablo headerlarımız farklı 

### ISSUE THREAD

**Issue by barslmn** [gen-era/canvas#16]
Buradaki tablo headerlarımız farklı 
https://github.com/gen-era/canvas/blob/60d36e14029dd4c5d5eb667e3923b36216b6be53/canvas/templates/canvas/components/sample_input.html

https://github.com/gen-era/canvas/blob/60d36e14029dd4c5d5eb667e3923b36216b6be53/canvas/templates/canvas/partials/samples_from_excel.html

**Comment by yserdem** [comment]
düzenlendi
